AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ConfigFileLocation:
    Description: Provide the S3 location of the survey configuration file.
      For example, if the location is "s3://my-config-bucket/config.yaml,"" enter "my-config-bucket/config.yaml.""
    Type: String

Resources:
  SurveyConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - s3:*
                Resource: !Sub "arn:aws:s3:::${ConfigFileLocation}"
                Effect: Allow
          PolicyName: config-file-s3-access
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  SurveyStack:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:910000848896:applications/serverless-survey-external-config
        SemanticVersion: 0.0.1
      Parameters:
        ConfigFileLocation: !Ref ConfigFileLocation